# Name your project
name: 'medical_warehouse'
version: '1.0.0'

# Profile to use for connections
profile: 'medical_warehouse'

# Paths to your dbt files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# All models in medical_warehouse/ will be materialized as views by default
models:
  medical_warehouse:
    +materialized: view
