version: 2

models:

  - name: stg_telegram_messages
    description: "Staging table for Telegram messages"
    columns:
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: message_date
        description: "Date of the message"
        tests:
          - not_null
      - name: message_id
        description: "Unique message identifier"
        tests:
          - not_null
          - unique
      - name: message_text
        description: "Text content of the message"
        tests:
          - not_null
